// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	BROWSER: DurableObjectNamespace;
	MYBROWSER: BrowserWorker;
	MD_CACHE: KVNamespace;
	RATELIMITER: any;
	AI: Ai
}


declare const Readability: any;
declare const TurndownService: any;
declare const document: any;
